cmake_minimum_required(VERSION 3.20)
foreach(required AMB_BUILD_DIR AMB_MINGW_ROOT AMB_FILTER_DIR AMB_OUTPUT_DIR)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "Missing ${required}")
    endif()
endforeach()
get_filename_component(repo "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
file(STRINGS "${repo}/VERSION" version LIMIT_COUNT 1)
if(DEFINED AMB_PACKAGE_VERSION)
    set(version "${AMB_PACKAGE_VERSION}")
endif()
set(name "Mobile_Webcam-${version}-windows-x86_64-experimental")
if(DEFINED AMB_RUST_EXECUTABLE)
    if(NOT DEFINED AMB_FFMPEG_ROOT OR NOT DEFINED AMB_RUST_LICENSES)
        message(FATAL_ERROR "Rust packaging needs the minimal FFmpeg prefix and generated licenses")
    endif()
    set(name "Mobile_Webcam-${version}-windows-x86_64-rust-preview")
endif()
set(stage "${AMB_OUTPUT_DIR}/${name}")
if(EXISTS "${stage}")
    message(FATAL_ERROR "Remove the old staging directory before packaging: ${stage}")
endif()
set(plugin)
if(DEFINED AMB_RUST_EXECUTABLE)
    set(executables "${AMB_RUST_EXECUTABLE}")
else()
    set(executables)
    foreach(tool mobile-webcam amb-aoa-probe amb-windows-sink)
        list(APPEND executables "${AMB_BUILD_DIR}/${tool}.exe")
    endforeach()
    set(plugin "${AMB_MINGW_ROOT}/share/qt6/plugins/platforms/qwindows.dll")
endif()
set(CMAKE_GET_RUNTIME_DEPENDENCIES_PLATFORM windows+pe)
set(CMAKE_GET_RUNTIME_DEPENDENCIES_TOOL objdump)
if(DEFINED AMB_OBJDUMP)
    set(CMAKE_GET_RUNTIME_DEPENDENCIES_COMMAND "${AMB_OBJDUMP}")
else()
    set(CMAKE_GET_RUNTIME_DEPENDENCIES_COMMAND "${AMB_MINGW_ROOT}/bin/objdump.exe")
endif()
set(runtime_directories "${AMB_MINGW_ROOT}/bin" ${AMB_SYSTEM_DLL_DIR})
if(DEFINED AMB_FFMPEG_ROOT)
    list(PREPEND runtime_directories "${AMB_FFMPEG_ROOT}/bin")
endif()
file(GET_RUNTIME_DEPENDENCIES
    EXECUTABLES ${executables} LIBRARIES ${plugin}
    DIRECTORIES ${runtime_directories}
    PRE_EXCLUDE_REGEXES "^[Aa][Pp][Ii]-" "^[Ee][Xx][Tt]-"
                       "^[Dd]3[Dd].*\\.dll$" "^[Dd][Xx][Gg][Ii]\\.dll$"
                       "^[Oo][Pp][Ee][Nn][Gg][Ll]32\\.dll$" "^[Gg][Ll][Uu]32\\.dll$"
    POST_EXCLUDE_REGEXES ".*[Ww][Ii][Nn][Dd][Oo][Ww][Ss]/[Ss][Yy][Ss][Tt][Ee][Mm]32/.*"
    RESOLVED_DEPENDENCIES_VAR dependencies
    UNRESOLVED_DEPENDENCIES_VAR unresolved)
if(unresolved)
    message(FATAL_ERROR "Unresolved Windows runtime dependencies: ${unresolved}")
endif()
file(MAKE_DIRECTORY "${stage}/virtual-camera" "${stage}/licenses")
file(COPY ${executables} DESTINATION "${stage}")
if(plugin)
    file(COPY "${plugin}" DESTINATION "${stage}/platforms")
endif()
foreach(dependency IN LISTS dependencies)
    # System DLLs remain provided by Windows; copy only the chosen MinGW environment.
    cmake_path(IS_PREFIX AMB_MINGW_ROOT "${dependency}" NORMALIZE from_mingw)
    set(from_ffmpeg false)
    if(DEFINED AMB_FFMPEG_ROOT)
        cmake_path(IS_PREFIX AMB_FFMPEG_ROOT "${dependency}" NORMALIZE from_ffmpeg)
    endif()
    if(DEFINED AMB_RUST_EXECUTABLE AND dependency MATCHES "[Qq]t[56]|avformat|avdevice|avfilter|swresample")
        message(FATAL_ERROR "Unexpected Rust runtime dependency: ${dependency}")
    endif()
    if(DEFINED AMB_RUST_EXECUTABLE AND dependency MATCHES "(avcodec|avutil|swscale).*\\.dll$" AND NOT from_ffmpeg)
        message(FATAL_ERROR "FFmpeg must come from the minimal build: ${dependency}")
    endif()
    if(from_mingw OR from_ffmpeg)
        file(COPY "${dependency}" DESTINATION "${stage}")
    endif()
endforeach()
if(plugin)
    file(WRITE "${stage}/qt.conf" "[Paths]\nPlugins=.\n")
endif()
file(STRINGS "${repo}/windows/unity-capture.sha256" filter_hashes)
foreach(entry IN LISTS filter_hashes)
    string(REPLACE "  " ";" pair "${entry}")
    list(GET pair 0 expected_hash)
    list(GET pair 1 filter)
    file(SHA256 "${AMB_FILTER_DIR}/${filter}" actual_hash)
    if(NOT actual_hash STREQUAL expected_hash)
        message(FATAL_ERROR "Camera DLL checksum mismatch: ${filter}")
    endif()
    file(COPY "${AMB_FILTER_DIR}/${filter}" DESTINATION "${stage}/virtual-camera")
endforeach()
file(COPY "${repo}/LICENSE" "${repo}/NOTICE" "${repo}/THIRD_PARTY_NOTICES.md" DESTINATION "${stage}")
if(DEFINED AMB_RUST_EXECUTABLE)
    file(COPY "${repo}/host-rs/README.md" DESTINATION "${stage}")
else()
    file(COPY "${repo}/windows/README.md" DESTINATION "${stage}")
endif()
file(COPY "${repo}/host/third_party/unity_capture/LICENSE"
     DESTINATION "${stage}/licenses/unity-capture")
if(DEFINED AMB_RUST_EXECUTABLE)
    file(COPY "${AMB_RUST_LICENSES}/" DESTINATION "${stage}/licenses/rust")
    foreach(library libgcc libusb libwinpthread)
        file(COPY "${AMB_MINGW_ROOT}/share/licenses/${library}" DESTINATION "${stage}/licenses/msys2")
    endforeach()
    file(COPY "${repo}/linux/licenses/LGPL-2.1-or-later.txt" "${AMB_FFMPEG_ROOT}/build-manifest.json"
         DESTINATION "${stage}/licenses/ffmpeg")
    file(COPY "${repo}/host-rs/tools/build_ffmpeg.py" DESTINATION "${stage}/licenses/ffmpeg")
    file(WRITE "${stage}/licenses/ffmpeg/SOURCE.txt" "FFmpeg source: https://ffmpeg.org/releases/ffmpeg-9.0.2.tar.xz\nReproduce using host-rs/tools/build_ffmpeg.py and the accompanying build manifest.\n")
    find_program(AMB_PYTHON NAMES python3 python REQUIRED)
    execute_process(COMMAND "${AMB_PYTHON}" "${repo}/host-rs/tools/verify_distribution.py"
        windows "${stage}" --objdump "${CMAKE_GET_RUNTIME_DEPENDENCIES_COMMAND}"
        OUTPUT_QUIET COMMAND_ERROR_IS_FATAL ANY)
    file(GLOB_RECURSE size_files "${stage}/*")
    set(expanded_size 0)
    foreach(path IN LISTS size_files)
        file(SIZE "${path}" size)
        math(EXPR expanded_size "${expanded_size}+${size}")
    endforeach()
    if(expanded_size GREATER 62914560)
        message(FATAL_ERROR "Rust distribution exceeds the 60 MiB budget: ${expanded_size}")
    endif()
    message(STATUS "Rust expanded distribution: ${expanded_size} bytes")
else()
    file(COPY "${AMB_MINGW_ROOT}/share/licenses/" DESTINATION "${stage}/licenses/msys2")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" -E tar cf "${AMB_OUTPUT_DIR}/${name}.zip"
                        --format=zip "${name}" WORKING_DIRECTORY "${AMB_OUTPUT_DIR}"
                COMMAND_ERROR_IS_FATAL ANY)
message(STATUS "Created ${AMB_OUTPUT_DIR}/${name}.zip")

# Use the exact staged file list for deletion; never recursively erase user files.
file(GLOB_RECURSE staged_files RELATIVE "${stage}" "${stage}/*")
set(delete_manifest "${AMB_OUTPUT_DIR}/${name}-delete.nsh")
file(WRITE "${delete_manifest}" "!macro DeleteApplicationFiles\n")
foreach(relative IN LISTS staged_files)
    if(relative MATCHES "^virtual-camera/")
        continue()
    endif()
    string(REPLACE "/" "\\" windows_relative "${relative}")
    file(APPEND "${delete_manifest}" "Delete \"$INSTDIR\\${windows_relative}\"\n")
endforeach()
file(APPEND "${delete_manifest}" "!macroend\n!macro DeleteCameraFiles\n")
foreach(relative IN LISTS staged_files)
    if(relative MATCHES "^virtual-camera/")
        string(REPLACE "/" "\\" windows_relative "${relative}")
        file(APPEND "${delete_manifest}" "Delete \"$INSTDIR\\${windows_relative}\"\n")
    endif()
endforeach()
file(APPEND "${delete_manifest}" "!macroend\n!macro DeleteApplicationDirectories\n")
file(GLOB_RECURSE staged_paths LIST_DIRECTORIES true RELATIVE "${stage}" "${stage}/*")
list(SORT staged_paths ORDER DESCENDING)
foreach(relative IN LISTS staged_paths)
    if(IS_DIRECTORY "${stage}/${relative}")
        string(REPLACE "/" "\\" windows_relative "${relative}")
        file(APPEND "${delete_manifest}" "RMDir \"$INSTDIR\\${windows_relative}\"\n")
    endif()
endforeach()
file(APPEND "${delete_manifest}" "!macroend\n")
if(NOT DEFINED AMB_MAKENSIS)
    find_program(AMB_MAKENSIS NAMES makensis REQUIRED)
endif()
set(installer "${AMB_OUTPUT_DIR}/${name}-Setup.exe")
execute_process(COMMAND ${AMB_MAKENSIS} -V2 -WX
    "-DAMB_VERSION=${version}" "-DAMB_STAGE=${stage}" "-DAMB_INSTALLER=${installer}"
    "-DAMB_DELETE_MANIFEST=${delete_manifest}" -- "${repo}/windows/installer.nsi"
    COMMAND_ERROR_IS_FATAL ANY)
message(STATUS "Created ${installer}")
